packages:
  - packages/*
  - web

overrides:
  mdast-util-gfm-autolink-literal: 2.0.0

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
