import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

i18n
	// detect user language
	// learn more: https://github.com/i18next/i18next-browser-languageDetector
	.use(LanguageDetector)
	// pass the i18n instance to react-i18next.
	.use(initReactI18next)
	// init i18next
	// for all options read: https://www.i18next.com/overview/configuration-options
	.init({
		debug: true,
		fallbackLng: 'en',
		interpolation: {
			escapeValue: false, // not needed for react as it escapes by default
		},
		resources: {
			en: {
				translation: {
					app: {
						list: 'App List',
						no_description: 'No description',
						no_config_default_text: 'No Dify app config found, please contact the administrator.',
					},
					chat: {
						new_chat: 'New Chat',
						sidebar_close: 'Close Sidebar',
						sidebar_open: 'Open Sidebar',
						no_config_default_text: 'No Dify app config found, please contact the administrator.',
						input_params_setting: 'Input Parameters Setting',
						input_disabled_between_chats:
							'Attention: Params will be reaonly if the conversation starts.',
					},
					system: {
						default_disclaimer_content: 'Content generated by AI, for reference only.',
					},
				},
			},
			zh: {
				translation: {
					app: {
						list: '应用列表',
						no_description: '暂无描述',
					},
					chat: {
						new_chat: '新增对话',
						sidebar_close: '折叠侧边栏',
						sidebar_open: '展开侧边栏',
						no_config_default_text: '暂无 Dify 应用配置，请联系管理员',
						input_params_setting: '对话参数设置',
						input_disabled_between_chats: '注意：对话开始后，参数设置将无法修改',
					},
					system: {
						default_disclaimer_content: '内容由 AI 生成, 仅供参考',
					},
				},
			},
		},
	})

export default i18n
