import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

i18n
	// detect user language
	// learn more: https://github.com/i18next/i18next-browser-languageDetector
	.use(LanguageDetector)
	// pass the i18n instance to react-i18next.
	.use(initReactI18next)
	// init i18next
	// for all options read: https://www.i18next.com/overview/configuration-options
	.init({
		debug: true,
		fallbackLng: 'en',
		interpolation: {
			escapeValue: false, // not needed for react as it escapes by default
		},
		resources: {
			en: {
				translation: {
					app: {
						list: 'App List',
					},
					chat: {
						new_chat: 'New Chat',
						sidebar_close: 'Close Sidebar',
						sidebar_open: 'Open Sidebar',
					},
					system: {
						default_disclaimer_content: 'Content generated by AI, for reference only.',
					},
				},
			},
			zh: {
				translation: {
					app: {
						list: '应用列表',
					},
					chat: {
						new_chat: '新增对话',
						sidebar_close: '折叠侧边栏',
						sidebar_open: '展开侧边栏',
					},
					system: {
						default_disclaimer_content: '内容由 AI 生成, 仅供参考',
					},
				},
			},
		},
	})

export default i18n
